type UiCopy = {
  statusReady: string;
  statusListening: string;
  statusWorking: string;
  languageWord: string;
  from: string;
  to: string;
  record: string;
  stop: string;
  listen: string;
  playing: string;
  resultLabel: string;
  resultTitle: string;
  speechResultTitle: string;
  resultPlaceholder: string;
  voiceReady: string;
  inputLabel: string;
  inputTitle: string;
  inputRecordingTitle: string;
  inputPlaceholder: string;
  translate: string;
  translating: string;
  chooseLanguage: string;
  searchLanguage: string;
  noLanguageFound: string;
  tryAnotherWord: string;
  alertTranslateFailedTitle: string;
  alertSpeechFailedTitle: string;
  alertWebNeededTitle: string;
  alertWebNeededMessage: string;
  alertMicPermissionTitle: string;
  alertMicPermissionMessage: string;
  alertNoOutputTitle: string;
  alertNoOutputMessage: string;
  alertVoiceUnavailableTitle: string;
};

const ENGLISH_UI: UiCopy = {
  statusReady: 'Ready',
  statusListening: 'Listening',
  statusWorking: 'Translating',
  languageWord: 'languages',
  from: 'From',
  to: 'To',
  record: 'Speak',
  stop: 'Stop',
  listen: 'Listen',
  playing: 'Playing',
  resultLabel: 'Result',
  resultTitle: 'Result',
  speechResultTitle: 'Speech result',
  resultPlaceholder: 'Translation will appear here',
  voiceReady: 'Audio ready',
  inputLabel: 'Input',
  inputTitle: 'Type or speak',
  inputRecordingTitle: 'Recording',
  inputPlaceholder: 'Type here',
  translate: 'Translate',
  translating: 'Translating',
  chooseLanguage: 'Choose language',
  searchLanguage: 'Search language',
  noLanguageFound: 'No language found',
  tryAnotherWord: 'Try another word',
  alertTranslateFailedTitle: 'Translation failed',
  alertSpeechFailedTitle: 'Speech translation failed',
  alertWebNeededTitle: 'Web needed',
  alertWebNeededMessage: 'Use web for recording in this build.',
  alertMicPermissionTitle: 'Microphone access needed',
  alertMicPermissionMessage: 'Allow microphone access to record.',
  alertNoOutputTitle: 'Translate first',
  alertNoOutputMessage: 'Then play the audio.',
  alertVoiceUnavailableTitle: 'Audio unavailable',
};

const UI_COPY: Record<string, Partial<UiCopy>> = {
  English: {},
  Assamese: {
    statusReady: 'প্ৰস্তুত',
    statusListening: 'শুনিছে',
    statusWorking: 'অনুবাদ চলি আছে',
    languageWord: 'ভাষা',
    from: 'পৰা',
    to: 'লৈ',
    record: 'কওক',
    stop: 'বন্ধ',
    listen: 'শুনক',
    playing: 'চলি আছে',
    resultLabel: 'ফলাফল',
    resultTitle: 'ফলাফল',
    speechResultTitle: 'কথাৰ ফলাফল',
    resultPlaceholder: 'অনুবাদ ইয়াত দেখা যাব',
    voiceReady: 'অডিঅ’ সাজু',
    inputLabel: 'ইনপুট',
    inputTitle: 'লিখক বা কওক',
    inputRecordingTitle: 'ৰেকৰ্ডিং',
    inputPlaceholder: 'ইয়াত লিখক',
    translate: 'অনুবাদ কৰক',
    translating: 'অনুবাদ হৈ আছে',
    chooseLanguage: 'ভাষা বাছক',
    searchLanguage: 'ভাষা বিচাৰক',
    noLanguageFound: 'ভাষা পোৱা নগ’ল',
    tryAnotherWord: 'আন শব্দ চেষ্টা কৰক',
    alertTranslateFailedTitle: 'অনুবাদ নহ’ল',
    alertSpeechFailedTitle: 'কথাৰ অনুবাদ নহ’ল',
    alertWebNeededTitle: 'ৱেব লাগিব',
    alertWebNeededMessage: 'এই বিল্ডত ৰেকৰ্ডিংৰ বাবে ৱেব ব্যৱহাৰ কৰক।',
    alertMicPermissionTitle: 'মাইক অনুমতি লাগিব',
    alertMicPermissionMessage: 'ৰেকৰ্ডিংৰ বাবে মাইকৰ অনুমতি দিয়ক।',
    alertNoOutputTitle: 'আগে অনুবাদ কৰক',
    alertNoOutputMessage: 'তাৰ পিছত অডিঅ’ শুনক।',
    alertVoiceUnavailableTitle: 'অডিঅ’ উপলব্ধ নহয়',
  },
  Bodo: {
    statusReady: 'थियार',
    statusListening: 'गाबगासिनो दङ',
    statusWorking: 'रावसोलायनाय गैया',
    languageWord: 'राव',
    from: 'निफ्राय',
    to: 'सिम',
    record: 'बुङो',
    stop: 'दां',
    listen: 'गासै',
    playing: 'चालू',
    resultLabel: 'फिथाइ',
    resultTitle: 'फिथाइ',
    speechResultTitle: 'बुङनाय फिथाइ',
    resultPlaceholder: 'रावसोलायनाय बेयाव नुजागोन',
    voiceReady: 'अडिअ थियार',
    inputLabel: 'इनपुट',
    inputTitle: 'लिखो एबा बुङो',
    inputRecordingTitle: 'रेकर्डिं',
    inputPlaceholder: 'बेयाव लिखो',
    translate: 'रावसोलाय',
    translating: 'रावसोलायनाय गैया',
    chooseLanguage: 'राव बासिख',
    searchLanguage: 'राव नागिर',
    noLanguageFound: 'राव मोननो हायाखै',
    tryAnotherWord: 'गुबुन सोदोब नागिर',
    alertTranslateFailedTitle: 'रावसोलायनाय जाया',
    alertSpeechFailedTitle: 'बुङनाय रावसोलायनाय जाया',
    alertWebNeededTitle: 'वेब नांगौ',
    alertWebNeededMessage: 'बे बिल्डआव रेकर्डिंनि थाखाय वेब बाहाय।',
    alertMicPermissionTitle: 'माइकनि गनायथि नांगौ',
    alertMicPermissionMessage: 'रेकर्डिंनि थाखाय माइकनि गनायथि हो।',
    alertNoOutputTitle: 'सिगां रावसोलाय',
    alertNoOutputMessage: 'बेनि उनाव अडिअ गासै।',
    alertVoiceUnavailableTitle: 'अडिअ गैया',
  },
  Dogri: {
    statusReady: 'त्यार',
    statusListening: 'सुनी रेहा ऐ',
    statusWorking: 'अनुवाद होई रेहा ऐ',
    languageWord: 'भाषा',
    from: 'तों',
    to: 'च',
    record: 'बोलो',
    stop: 'रुको',
    listen: 'सुणो',
    playing: 'चलदा ऐ',
    resultLabel: 'नतीजा',
    resultTitle: 'नतीजा',
    speechResultTitle: 'आवाज दा नतीजा',
    resultPlaceholder: 'अनुवाद इत्थै दिस्सेगा',
    voiceReady: 'आवाज त्यार ऐ',
    inputLabel: 'इनपुट',
    inputTitle: 'लिखो जां बोलो',
    inputRecordingTitle: 'रिकार्डिंग',
    inputPlaceholder: 'इत्थै लिखो',
    translate: 'अनुवाद करो',
    translating: 'अनुवाद होई रेहा ऐ',
    chooseLanguage: 'भाषा चुनो',
    searchLanguage: 'भाषा लैब्भो',
    noLanguageFound: 'कोई भाषा नेईं मिली',
    tryAnotherWord: 'दूजा शब्द लिखो',
    alertTranslateFailedTitle: 'अनुवाद नेईं होया',
    alertSpeechFailedTitle: 'आवाज दा अनुवाद नेईं होया',
    alertWebNeededTitle: 'वेब चाहिदा ऐ',
    alertWebNeededMessage: 'इस बिल्ड च रिकार्डिंग लेई वेब दा इस्तेमाल करो।',
    alertMicPermissionTitle: 'माइक दी इजाजत चाहिदी ऐ',
    alertMicPermissionMessage: 'रिकार्डिंग लेई माइक दी इजाजत देओ।',
    alertNoOutputTitle: 'पैहले अनुवाद करो',
    alertNoOutputMessage: 'फिर आवाज सुणो।',
    alertVoiceUnavailableTitle: 'आवाज उपलब्ध नेईं ऐ',
  },
  Gujarati: {
    statusReady: 'તૈયાર',
    statusListening: 'સાંભળી રહ્યું છે',
    statusWorking: 'અનુવાદ ચાલી રહ્યો છે',
    languageWord: 'ભાષાઓ',
    from: 'થી',
    to: 'માં',
    record: 'બોલો',
    stop: 'બંધ',
    listen: 'સાંભળો',
    playing: 'ચાલી રહ્યું છે',
    resultLabel: 'પરિણામ',
    resultTitle: 'પરિણામ',
    speechResultTitle: 'આવાજ પરિણામ',
    resultPlaceholder: 'અનુવાદ અહીં દેખાશે',
    voiceReady: 'આવાજ તૈયાર',
    inputLabel: 'ઇનપુટ',
    inputTitle: 'લખો અથવા બોલો',
    inputRecordingTitle: 'રેકોર્ડિંગ',
    inputPlaceholder: 'અહીં લખો',
    translate: 'અનુવાદ કરો',
    translating: 'અનુવાદ થઈ રહ્યો છે',
    chooseLanguage: 'ભાષા પસંદ કરો',
    searchLanguage: 'ભાષા શોધો',
    noLanguageFound: 'ભાષા મળી નહીં',
    tryAnotherWord: 'બીજો શબ્દ લખો',
    alertTranslateFailedTitle: 'અનુવાદ થયો નહીં',
    alertSpeechFailedTitle: 'આવાજનો અનુવાદ થયો નહીં',
    alertWebNeededTitle: 'વેબ જરૂરી છે',
    alertWebNeededMessage: 'આ બિલ્ડમાં રેકોર્ડિંગ માટે વેબનો ઉપયોગ કરો.',
    alertMicPermissionTitle: 'માઇક્રોફોન પરવાનગી જોઈએ',
    alertMicPermissionMessage: 'રેકોર્ડિંગ માટે માઇક્રોફોનની પરવાનગી આપો.',
    alertNoOutputTitle: 'પહેલા અનુવાદ કરો',
    alertNoOutputMessage: 'પછી અવાજ સાંભળો.',
    alertVoiceUnavailableTitle: 'આવાજ ઉપલબ્ધ નથી',
  },
  Hindi: {
    statusReady: 'तैयार',
    statusListening: 'सुन रहा है',
    statusWorking: 'अनुवाद चल रहा है',
    languageWord: 'भाषाएँ',
    from: 'से',
    to: 'में',
    record: 'बोलें',
    stop: 'रोकें',
    listen: 'सुनें',
    playing: 'चल रहा है',
    resultLabel: 'अनुवाद',
    resultTitle: 'परिणाम',
    speechResultTitle: 'सुनकर अनुवाद',
    resultPlaceholder: 'अनुवाद यहां दिखेगा',
    voiceReady: 'आवाज़ तैयार है',
    inputLabel: 'इनपुट',
    inputTitle: 'लिखें या बोलें',
    inputRecordingTitle: 'रिकॉर्डिंग',
    inputPlaceholder: 'यहां लिखें',
    translate: 'अनुवाद करें',
    translating: 'अनुवाद हो रहा है',
    chooseLanguage: 'भाषा चुनें',
    searchLanguage: 'भाषा खोजें',
    noLanguageFound: 'कोई भाषा नहीं मिली',
    tryAnotherWord: 'दूसरा शब्द लिखें',
    alertTranslateFailedTitle: 'अनुवाद नहीं हुआ',
    alertSpeechFailedTitle: 'आवाज़ अनुवाद नहीं हुआ',
    alertWebNeededTitle: 'वेब की ज़रूरत है',
    alertWebNeededMessage: 'इस बिल्ड में रिकॉर्डिंग के लिए वेब का उपयोग करें।',
    alertMicPermissionTitle: 'माइक्रोफ़ोन अनुमति चाहिए',
    alertMicPermissionMessage: 'रिकॉर्डिंग के लिए माइक्रोफ़ोन की अनुमति दें।',
    alertNoOutputTitle: 'पहले अनुवाद करें',
    alertNoOutputMessage: 'उसके बाद आवाज़ सुनें।',
    alertVoiceUnavailableTitle: 'आवाज़ उपलब्ध नहीं है',
  },
  Kannada: {
    statusReady: 'ಸಿದ್ಧ',
    statusListening: 'ಕೇಳುತ್ತಿದೆ',
    statusWorking: 'ಅನುವಾದ ನಡೆಯುತ್ತಿದೆ',
    languageWord: 'ಭಾಷೆಗಳು',
    from: 'ಇಂದ',
    to: 'ಗೆ',
    record: 'ಮಾತನಾಡಿ',
    stop: 'ನಿಲ್ಲಿಸಿ',
    listen: 'ಕೇಳಿ',
    playing: 'ಚಲಿಸುತ್ತಿದೆ',
    resultLabel: 'ಫಲಿತಾಂಶ',
    resultTitle: 'ಫಲಿತಾಂಶ',
    speechResultTitle: 'ಧ್ವನಿ ಫಲಿತಾಂಶ',
    resultPlaceholder: 'ಅನುವಾದ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ',
    voiceReady: 'ಧ್ವನಿ ಸಿದ್ಧ',
    inputLabel: 'ಇನ್‌ಪುಟ್',
    inputTitle: 'ಬರೆಯಿರಿ ಅಥವಾ ಮಾತನಾಡಿ',
    inputRecordingTitle: 'ದಾಖಲೆ',
    inputPlaceholder: 'ಇಲ್ಲಿ ಬರೆಯಿರಿ',
    translate: 'ಅನುವಾದಿಸಿ',
    translating: 'ಅನುವಾದ ಆಗುತ್ತಿದೆ',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    searchLanguage: 'ಭಾಷೆ ಹುಡುಕಿ',
    noLanguageFound: 'ಭಾಷೆ ಸಿಕ್ಕಿಲ್ಲ',
    tryAnotherWord: 'ಬೇರೆ ಪದ ಪ್ರಯತ್ನಿಸಿ',
    alertTranslateFailedTitle: 'ಅನುವಾದ ಆಗಲಿಲ್ಲ',
    alertSpeechFailedTitle: 'ಧ್ವನಿ ಅನುವಾದ ಆಗಲಿಲ್ಲ',
    alertWebNeededTitle: 'ವೆಬ್ ಬೇಕಾಗಿದೆ',
    alertWebNeededMessage: 'ಈ ಬಿಲ್ಡ್‌ನಲ್ಲಿ ದಾಖಲೆಗಾಗಿ ವೆಬ್ ಬಳಸಿ.',
    alertMicPermissionTitle: 'ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ಬೇಕು',
    alertMicPermissionMessage: 'ದಾಖಲೆಗೆ ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನೀಡಿ.',
    alertNoOutputTitle: 'ಮೊದಲು ಅನುವಾದಿಸಿ',
    alertNoOutputMessage: 'ನಂತರ ಧ್ವನಿ ಕೇಳಿ.',
    alertVoiceUnavailableTitle: 'ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ',
  },
  Kashmiri: {
    statusReady: 'تیار',
    statusListening: 'سنان چھُ',
    statusWorking: 'ترجمہ چُلان',
    languageWord: 'زٕبان',
    from: 'منز',
    to: 'سُد',
    record: 'بوٚلو',
    stop: 'بند',
    listen: 'سنو',
    playing: 'چل رہا ہے',
    resultLabel: 'نتیجہ',
    resultTitle: 'نتیجہ',
    speechResultTitle: 'آواز نتیجہ',
    resultPlaceholder: 'ترجمہ یتھ ظاہِر گژھِہ',
    voiceReady: 'آواز تیار',
    inputLabel: 'اِنپُٹ',
    inputTitle: 'لِکھو یا بوٚلو',
    inputRecordingTitle: 'ریکارڈنگ',
    inputPlaceholder: 'یہتہ لِکھو',
    translate: 'ترجمہ کرو',
    translating: 'ترجمہ چُلان',
    chooseLanguage: 'زٕبان ژٕرِن',
    searchLanguage: 'زٕبان ژھانڈو',
    noLanguageFound: 'زٕبان مِل نہٕ',
    tryAnotherWord: 'دوسرا لفظ لِکھو',
    alertTranslateFailedTitle: 'ترجمہ نہٕ آو',
    alertSpeechFailedTitle: 'آواز ترجمہ نہٕ آو',
    alertWebNeededTitle: 'ویب ضروری',
    alertWebNeededMessage: 'اس بِلد منز ریکارڈنگ خٲطرٕ ویب استعمال کٔریو۔',
    alertMicPermissionTitle: 'مایک اجازت ضروری',
    alertMicPermissionMessage: 'ریکارڈنگ خٲطرٕ مایک اجازت دِیو۔',
    alertNoOutputTitle: 'پہلے ترجمہ کرو',
    alertNoOutputMessage: 'پتہ آواز سنو۔',
    alertVoiceUnavailableTitle: 'آواز دستیاب نہٕ',
  },
  Konkani: {
    statusReady: 'तयार',
    statusListening: 'आयकता',
    statusWorking: 'भाशांतर जाता',
    languageWord: 'भासा',
    from: 'सांव',
    to: 'मधीं',
    record: 'उलोव',
    stop: 'थांब',
    listen: 'आयक',
    playing: 'चालू आसा',
    resultLabel: 'परिणाम',
    resultTitle: 'परिणाम',
    speechResultTitle: 'आवाज परिणाम',
    resultPlaceholder: 'भाशांतर हांगां दिसतलें',
    voiceReady: 'आवाज तयार',
    inputLabel: 'इनपुट',
    inputTitle: 'लिखात वा उलोव',
    inputRecordingTitle: 'रेकॉर्डिंग',
    inputPlaceholder: 'हांगां लिखात',
    translate: 'भाशांतर कर',
    translating: 'भाशांतर जाता',
    chooseLanguage: 'भास निवड',
    searchLanguage: 'भास सोद',
    noLanguageFound: 'भास मेळ्ळी ना',
    tryAnotherWord: 'दुसरो शब्द लिखात',
    alertTranslateFailedTitle: 'भाशांतर जालें ना',
    alertSpeechFailedTitle: 'आवाजाचें भाशांतर जालें ना',
    alertWebNeededTitle: 'वेब जाय',
    alertWebNeededMessage: 'ह्या बिल्डांत रेकॉर्डिंग खातीर वेब वापरात.',
    alertMicPermissionTitle: 'मायक परवानगी जाय',
    alertMicPermissionMessage: 'रेकॉर्डिंग खातीर मायक परवानगी दियात.',
    alertNoOutputTitle: 'आदें भाशांतर कर',
    alertNoOutputMessage: 'मगिर आवाज आयक.',
    alertVoiceUnavailableTitle: 'आवाज उपलब्ध ना',
  },
  Maithili: {
    statusReady: 'तैयार',
    statusListening: 'सुनि रहल अछि',
    statusWorking: 'अनुवाद चलि रहल अछि',
    languageWord: 'भाषा',
    from: 'सँ',
    to: 'मे',
    record: 'बोलू',
    stop: 'रोकू',
    listen: 'सुनू',
    playing: 'चलि रहल अछि',
    resultLabel: 'परिणाम',
    resultTitle: 'परिणाम',
    speechResultTitle: 'आवाज़ परिणाम',
    resultPlaceholder: 'अनुवाद एतय देखायत',
    voiceReady: 'आवाज़ तैयार अछि',
    inputLabel: 'इनपुट',
    inputTitle: 'लिखू वा बोलू',
    inputRecordingTitle: 'रिकॉर्डिंग',
    inputPlaceholder: 'एतय लिखू',
    translate: 'अनुवाद करू',
    translating: 'अनुवाद भऽ रहल अछि',
    chooseLanguage: 'भाषा चुनू',
    searchLanguage: 'भाषा खोजू',
    noLanguageFound: 'कोनो भाषा नहि भेटल',
    tryAnotherWord: 'दोसर शब्द लिखू',
    alertTranslateFailedTitle: 'अनुवाद नहि भेल',
    alertSpeechFailedTitle: 'आवाज़ अनुवाद नहि भेल',
    alertWebNeededTitle: 'वेब जरूरी अछि',
    alertWebNeededMessage: 'एहि बिल्ड मे रिकॉर्डिंग लेल वेबक उपयोग करू।',
    alertMicPermissionTitle: 'माइक्रोफोन अनुमति चाही',
    alertMicPermissionMessage: 'रिकॉर्डिंग लेल माइक्रोफोनक अनुमति दिअ।',
    alertNoOutputTitle: 'पहिने अनुवाद करू',
    alertNoOutputMessage: 'तकर बाद आवाज़ सुनू।',
    alertVoiceUnavailableTitle: 'आवाज़ उपलब्ध नहि अछि',
  },
  Malayalam: {
    statusReady: 'തയ്യാർ',
    statusListening: 'കേൾക്കുന്നു',
    statusWorking: 'പരിഭാഷ നടക്കുന്നു',
    languageWord: 'ഭാഷകൾ',
    from: 'നിന്ന്',
    to: 'ലേക്ക്',
    record: 'പറയൂ',
    stop: 'നിർത്തൂ',
    listen: 'കേൾക്കൂ',
    playing: 'നടക്കുന്നു',
    resultLabel: 'ഫലം',
    resultTitle: 'ഫലം',
    speechResultTitle: 'ശബ്ദ ഫലം',
    resultPlaceholder: 'പരിഭാഷ ഇവിടെ കാണും',
    voiceReady: 'ശബ്ദം തയ്യാറാണ്',
    inputLabel: 'ഇൻപുട്ട്',
    inputTitle: 'എഴുതുക അല്ലെങ്കിൽ പറയുക',
    inputRecordingTitle: 'റെക്കോർഡിംഗ്',
    inputPlaceholder: 'ഇവിടെ എഴുതുക',
    translate: 'പരിഭാഷ ചെയ്യുക',
    translating: 'പരിഭാഷ നടക്കുന്നു',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    searchLanguage: 'ഭാഷ തിരയുക',
    noLanguageFound: 'ഭാഷ കണ്ടെത്തിയില്ല',
    tryAnotherWord: 'മറ്റൊരു വാക്ക് ശ്രമിക്കുക',
    alertTranslateFailedTitle: 'പരിഭാഷയായില്ല',
    alertSpeechFailedTitle: 'ശബ്ദ പരിഭാഷയായില്ല',
    alertWebNeededTitle: 'വെബ് ആവശ്യമാണ്',
    alertWebNeededMessage: 'ഈ ബിൽഡിൽ റെക്കോർഡിംഗിന് വെബ് ഉപയോഗിക്കുക.',
    alertMicPermissionTitle: 'മൈക്രോഫോൺ അനുമതി വേണം',
    alertMicPermissionMessage: 'റെക്കോർഡിംഗിന് മൈക്രോഫോൺ അനുമതി നൽകുക.',
    alertNoOutputTitle: 'ആദ്യം പരിഭാഷ ചെയ്യുക',
    alertNoOutputMessage: 'അതിനുശേഷം ശബ്ദം കേൾക്കുക.',
    alertVoiceUnavailableTitle: 'ശബ്ദം ലഭ്യമല്ല',
  },
  Bengali: {
    statusReady: 'প্রস্তুত',
    statusListening: 'শুনছে',
    statusWorking: 'অনুবাদ চলছে',
    languageWord: 'ভাষা',
    from: 'থেকে',
    to: 'এ',
    record: 'বলুন',
    stop: 'থামান',
    listen: 'শুনুন',
    playing: 'চলছে',
    resultLabel: 'ফলাফল',
    resultTitle: 'ফলাফল',
    speechResultTitle: 'কথার ফলাফল',
    resultPlaceholder: 'অনুবাদ এখানে দেখা যাবে',
    voiceReady: 'অডিও প্রস্তুত',
    inputLabel: 'ইনপুট',
    inputTitle: 'লিখুন বা বলুন',
    inputRecordingTitle: 'রেকর্ডিং',
    inputPlaceholder: 'এখানে লিখুন',
    translate: 'অনুবাদ করুন',
    translating: 'অনুবাদ হচ্ছে',
    chooseLanguage: 'ভাষা বেছে নিন',
    searchLanguage: 'ভাষা খুঁজুন',
    noLanguageFound: 'কোনও ভাষা মেলেনি',
    tryAnotherWord: 'অন্য শব্দ লিখুন',
    alertTranslateFailedTitle: 'অনুবাদ হয়নি',
    alertSpeechFailedTitle: 'ভয়েস অনুবাদ হয়নি',
    alertWebNeededTitle: 'ওয়েব দরকার',
    alertWebNeededMessage: 'এই বিল্ডে রেকর্ডিংয়ের জন্য ওয়েব ব্যবহার করুন।',
    alertMicPermissionTitle: 'মাইক্রোফোন অনুমতি দরকার',
    alertMicPermissionMessage: 'রেকর্ডিংয়ের জন্য মাইক্রোফোনের অনুমতি দিন।',
    alertNoOutputTitle: 'আগে অনুবাদ করুন',
    alertNoOutputMessage: 'তারপর অডিও শুনুন।',
    alertVoiceUnavailableTitle: 'অডিও পাওয়া যাচ্ছে না',
  },
  Manipuri: {
    statusReady: 'তৈয়ার',
    statusListening: 'তাবগনি',
    statusWorking: 'অনুবাদ তৌরি',
    languageWord: 'লোন',
    from: 'দগি',
    to: 'দা',
    record: 'হায়ু',
    stop: 'লেপ্পু',
    listen: 'তাবু',
    playing: 'চৎলি',
    resultLabel: 'ফল',
    resultTitle: 'ফল',
    speechResultTitle: 'খোঙজেল ফল',
    resultPlaceholder: 'অনুবাদ মসিদা ওইগনি',
    voiceReady: 'অডিও তৈয়ার',
    inputLabel: 'ইনপুট',
    inputTitle: 'ইশিংবা হায়ু',
    inputRecordingTitle: 'রেকর্ডিং',
    inputPlaceholder: 'মসিদা ঈশিংউ',
    translate: 'অনুবাদ তৌ',
    translating: 'অনুবাদ তৌরি',
    chooseLanguage: 'লোন খল্লু',
    searchLanguage: 'লোন থিবা',
    noLanguageFound: 'লোন ফংদে',
    tryAnotherWord: 'অতোপ্পা ৱাহৈ লিখু',
    alertTranslateFailedTitle: 'অনুবাদ ওইদে',
    alertSpeechFailedTitle: 'খোঙজেল অনুবাদ ওইদে',
    alertWebNeededTitle: 'ওয়েব দরকার',
    alertWebNeededMessage: 'অসিগী বিল্ডদা রেকর্ডিংগী মমাংদা ওয়েব শিজিন্নু।',
    alertMicPermissionTitle: 'মাইক অনুমতি দরকার',
    alertMicPermissionMessage: 'রেকর্ডিং তৌনবা মাইক অনুমতি পীয়ু।',
    alertNoOutputTitle: 'অদোম্বা অনুবাদ তৌ',
    alertNoOutputMessage: 'অদুগা অডিও তাবু।',
    alertVoiceUnavailableTitle: 'অডিও লৈতে',
  },
  Marathi: {
    statusReady: 'तयार',
    statusListening: 'ऐकत आहे',
    statusWorking: 'भाषांतर सुरू आहे',
    languageWord: 'भाषा',
    from: 'पासून',
    to: 'मध्ये',
    record: 'बोला',
    stop: 'थांबा',
    listen: 'ऐका',
    playing: 'चालू आहे',
    resultLabel: 'निकाल',
    resultTitle: 'निकाल',
    speechResultTitle: 'आवाज निकाल',
    resultPlaceholder: 'भाषांतर येथे दिसेल',
    voiceReady: 'आवाज तयार आहे',
    inputLabel: 'इनपुट',
    inputTitle: 'लिहा किंवा बोला',
    inputRecordingTitle: 'रेकॉर्डिंग',
    inputPlaceholder: 'इथे लिहा',
    translate: 'भाषांतर करा',
    translating: 'भाषांतर होत आहे',
    chooseLanguage: 'भाषा निवडा',
    searchLanguage: 'भाषा शोधा',
    noLanguageFound: 'भाषा सापडली नाही',
    tryAnotherWord: 'दुसरा शब्द लिहा',
    alertTranslateFailedTitle: 'भाषांतर झाले नाही',
    alertSpeechFailedTitle: 'आवाजाचे भाषांतर झाले नाही',
    alertWebNeededTitle: 'वेबची गरज आहे',
    alertWebNeededMessage: 'या बिल्डमध्ये रेकॉर्डिंगसाठी वेब वापरा.',
    alertMicPermissionTitle: 'मायक्रोफोन परवानगी हवी',
    alertMicPermissionMessage: 'रेकॉर्डिंगसाठी मायक्रोफोनची परवानगी द्या.',
    alertNoOutputTitle: 'आधी भाषांतर करा',
    alertNoOutputMessage: 'नंतर आवाज ऐका.',
    alertVoiceUnavailableTitle: 'आवाज उपलब्ध नाही',
  },
  Nepali: {
    statusReady: 'तयार',
    statusListening: 'सुन्दैछ',
    statusWorking: 'अनुवाद हुँदैछ',
    languageWord: 'भाषा',
    from: 'बाट',
    to: 'मा',
    record: 'बोल्नुहोस्',
    stop: 'रोक्नुहोस्',
    listen: 'सुन्नुहोस्',
    playing: 'चल्दैछ',
    resultLabel: 'परिणाम',
    resultTitle: 'परिणाम',
    speechResultTitle: 'आवाज परिणाम',
    resultPlaceholder: 'अनुवाद यहाँ देखिनेछ',
    voiceReady: 'आवाज तयार छ',
    inputLabel: 'इनपुट',
    inputTitle: 'लेख्नुहोस् वा बोल्नुहोस्',
    inputRecordingTitle: 'रेकर्डिङ',
    inputPlaceholder: 'यहाँ लेख्नुहोस्',
    translate: 'अनुवाद गर्नुहोस्',
    translating: 'अनुवाद हुँदैछ',
    chooseLanguage: 'भाषा छान्नुहोस्',
    searchLanguage: 'भाषा खोज्नुहोस्',
    noLanguageFound: 'भाषा भेटिएन',
    tryAnotherWord: 'अर्को शब्द लेख्नुहोस्',
    alertTranslateFailedTitle: 'अनुवाद भएन',
    alertSpeechFailedTitle: 'आवाज अनुवाद भएन',
    alertWebNeededTitle: 'वेब चाहिन्छ',
    alertWebNeededMessage: 'यो बिल्डमा रेकर्डिङका लागि वेब प्रयोग गर्नुहोस्।',
    alertMicPermissionTitle: 'माइक्रोफोन अनुमति चाहिन्छ',
    alertMicPermissionMessage: 'रेकर्डिङका लागि माइक्रोफोन अनुमति दिनुहोस्।',
    alertNoOutputTitle: 'पहिले अनुवाद गर्नुहोस्',
    alertNoOutputMessage: 'त्यसपछि आवाज सुन्नुहोस्।',
    alertVoiceUnavailableTitle: 'आवाज उपलब्ध छैन',
  },
  Odia: {
    statusReady: 'ପ୍ରସ୍ତୁତ',
    statusListening: 'ଶୁଣୁଛି',
    statusWorking: 'ଅନୁବାଦ ଚାଲିଛି',
    languageWord: 'ଭାଷା',
    from: 'ରୁ',
    to: 'କୁ',
    record: 'କୁହନ୍ତୁ',
    stop: 'ବନ୍ଦ',
    listen: 'ଶୁଣନ୍ତୁ',
    playing: 'ଚାଲିଛି',
    resultLabel: 'ଫଳାଫଳ',
    resultTitle: 'ଫଳାଫଳ',
    speechResultTitle: 'ଶବ୍ଦ ଫଳାଫଳ',
    resultPlaceholder: 'ଅନୁବାଦ ଏଠାରେ ଦେଖାଯିବ',
    voiceReady: 'ଶବ୍ଦ ପ୍ରସ୍ତୁତ',
    inputLabel: 'ଇନପୁଟ',
    inputTitle: 'ଲେଖନ୍ତୁ କିମ୍ବା କୁହନ୍ତୁ',
    inputRecordingTitle: 'ରେକର୍ଡିଂ',
    inputPlaceholder: 'ଏଠାରେ ଲେଖନ୍ତୁ',
    translate: 'ଅନୁବାଦ କରନ୍ତୁ',
    translating: 'ଅନୁବାଦ ହେଉଛି',
    chooseLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    searchLanguage: 'ଭାଷା ଖୋଜନ୍ତୁ',
    noLanguageFound: 'ଭାଷା ମିଳିଲା ନାହିଁ',
    tryAnotherWord: 'ଅନ୍ୟ ଶବ୍ଦ ଲେଖନ୍ତୁ',
    alertTranslateFailedTitle: 'ଅନୁବାଦ ହେଲା ନାହିଁ',
    alertSpeechFailedTitle: 'ଶବ୍ଦ ଅନୁବାଦ ହେଲା ନାହିଁ',
    alertWebNeededTitle: 'ୱେବ ଆବଶ୍ୟକ',
    alertWebNeededMessage: 'ଏହି ବିଲ୍ଡରେ ରେକର୍ଡିଂ ପାଇଁ ୱେବ ବ୍ୟବହାର କରନ୍ତୁ।',
    alertMicPermissionTitle: 'ମାଇକ୍ରୋଫୋନ ଅନୁମତି ଦରକାର',
    alertMicPermissionMessage: 'ରେକର୍ଡିଂ ପାଇଁ ମାଇକ୍ରୋଫୋନ ଅନୁମତି ଦିଅନ୍ତୁ।',
    alertNoOutputTitle: 'ପ୍ରଥମେ ଅନୁବାଦ କରନ୍ତୁ',
    alertNoOutputMessage: 'ତାପରେ ଶବ୍ଦ ଶୁଣନ୍ତୁ।',
    alertVoiceUnavailableTitle: 'ଶବ୍ଦ ଉପଲବ୍ଧ ନାହିଁ',
  },
  Punjabi: {
    statusReady: 'ਤਿਆਰ',
    statusListening: 'ਸੁਣ ਰਿਹਾ ਹੈ',
    statusWorking: 'ਅਨੁਵਾਦ ਚੱਲ ਰਿਹਾ ਹੈ',
    languageWord: 'ਭਾਸ਼ਾਵਾਂ',
    from: 'ਤੋਂ',
    to: 'ਵਿੱਚ',
    record: 'ਬੋਲੋ',
    stop: 'ਰੋਕੋ',
    listen: 'ਸੁਣੋ',
    playing: 'ਚੱਲ ਰਿਹਾ ਹੈ',
    resultLabel: 'ਨਤੀਜਾ',
    resultTitle: 'ਨਤੀਜਾ',
    speechResultTitle: 'ਆਵਾਜ਼ ਨਤੀਜਾ',
    resultPlaceholder: 'ਅਨੁਵਾਦ ਇੱਥੇ ਵੇਖੇਗਾ',
    voiceReady: 'ਆਵਾਜ਼ ਤਿਆਰ ਹੈ',
    inputLabel: 'ਇਨਪੁੱਟ',
    inputTitle: 'ਲਿਖੋ ਜਾਂ ਬੋਲੋ',
    inputRecordingTitle: 'ਰਿਕਾਰਡਿੰਗ',
    inputPlaceholder: 'ਇੱਥੇ ਲਿਖੋ',
    translate: 'ਅਨੁਵਾਦ ਕਰੋ',
    translating: 'ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    searchLanguage: 'ਭਾਸ਼ਾ ਲੱਭੋ',
    noLanguageFound: 'ਕੋਈ ਭਾਸ਼ਾ ਨਹੀਂ ਮਿਲੀ',
    tryAnotherWord: 'ਹੋਰ ਸ਼ਬਦ ਲਿਖੋ',
    alertTranslateFailedTitle: 'ਅਨੁਵਾਦ ਨਹੀਂ ਹੋਇਆ',
    alertSpeechFailedTitle: 'ਆਵਾਜ਼ ਅਨੁਵਾਦ ਨਹੀਂ ਹੋਇਆ',
    alertWebNeededTitle: 'ਵੈੱਬ ਚਾਹੀਦਾ ਹੈ',
    alertWebNeededMessage: 'ਇਸ ਬਿਲਡ ਵਿੱਚ ਰਿਕਾਰਡਿੰਗ ਲਈ ਵੈੱਬ ਵਰਤੋ।',
    alertMicPermissionTitle: 'ਮਾਈਕ੍ਰੋਫੋਨ ਇਜਾਜ਼ਤ ਚਾਹੀਦੀ ਹੈ',
    alertMicPermissionMessage: 'ਰਿਕਾਰਡਿੰਗ ਲਈ ਮਾਈਕ੍ਰੋਫੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।',
    alertNoOutputTitle: 'ਪਹਿਲਾਂ ਅਨੁਵਾਦ ਕਰੋ',
    alertNoOutputMessage: 'ਫਿਰ ਆਵਾਜ਼ ਸੁਣੋ।',
    alertVoiceUnavailableTitle: 'ਆਵਾਜ਼ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
  },
  Sanskrit: {
    statusReady: 'सज्जम्',
    statusListening: 'शृणोति',
    statusWorking: 'अनुवादः चलति',
    languageWord: 'भाषाः',
    from: 'तः',
    to: 'मध्ये',
    record: 'वद',
    stop: 'स्थगय',
    listen: 'शृणु',
    playing: 'चलति',
    resultLabel: 'फलम्',
    resultTitle: 'फलम्',
    speechResultTitle: 'वाक्-फलम्',
    resultPlaceholder: 'अनुवादः अत्र दृश्यते',
    voiceReady: 'ध्वनिः सज्जा',
    inputLabel: 'आदानम्',
    inputTitle: 'लिख वा वद',
    inputRecordingTitle: 'ध्वनिलेखनम्',
    inputPlaceholder: 'अत्र लिख',
    translate: 'अनुवादं कुरु',
    translating: 'अनुवादः भवति',
    chooseLanguage: 'भाषां वृणु',
    searchLanguage: 'भाषां अन्विष',
    noLanguageFound: 'भाषा न लब्धा',
    tryAnotherWord: 'अन्यत् पदं लिख',
    alertTranslateFailedTitle: 'अनुवादः न अभवत्',
    alertSpeechFailedTitle: 'वाक्-अनुवादः न अभवत्',
    alertWebNeededTitle: 'वेब् अपेक्षितम्',
    alertWebNeededMessage: 'अस्यां निर्मितौ ध्वनिलेखनाय वेब् उपयुज्यताम्।',
    alertMicPermissionTitle: 'सूक्ष्मध्वनिग्राहक-अनुज्ञा अपेक्षिता',
    alertMicPermissionMessage: 'ध्वनिलेखनाय सूक्ष्मध्वनिग्राहक-अनुज्ञां ददातु।',
    alertNoOutputTitle: 'प्रथमं अनुवादं कुरु',
    alertNoOutputMessage: 'अनन्तरं ध्वनिं शृणु।',
    alertVoiceUnavailableTitle: 'ध्वनिः न उपलब्धा',
  },
  Santali: {
    statusReady: 'ᱛᱮᱭᱟᱨ',
    statusListening: 'ᱟᱭᱠᱟᱹᱜ ᱠᱟᱱᱟ',
    statusWorking: 'ᱛᱚᱨᱡᱚᱢᱟ ᱪᱟᱞᱟᱣ ᱠᱟᱱᱟ',
    languageWord: 'ᱯᱟᱹᱨᱥᱤ',
    from: 'ᱠᱷᱚᱱ',
    to: 'ᱨᱮ',
    record: 'ᱢᱮᱱ',
    stop: 'ᱛᱷᱟᱢ',
    listen: 'ᱟᱭᱠᱟᱹ',
    playing: 'ᱪᱟᱞᱟᱣ ᱠᱟᱱᱟ',
    resultLabel: 'ᱯᱷᱟᱹᱞ',
    resultTitle: 'ᱯᱷᱟᱹᱞ',
    speechResultTitle: 'ᱨᱟᱣ ᱯᱷᱟᱹᱞ',
    resultPlaceholder: 'ᱛᱚᱨᱡᱚᱢᱟ ᱱᱚᱸᱰᱮ ᱫᱤᱥᱚᱢ',
    voiceReady: 'ᱟᱣᱟᱡ ᱛᱮᱭᱟᱨ',
    inputLabel: 'ᱤᱱᱯᱩᱴ',
    inputTitle: 'ᱚᱞ ᱵᱟᱝ ᱢᱮᱱ',
    inputRecordingTitle: 'ᱨᱮᱠᱚᱨᱰᱤᱝ',
    inputPlaceholder: 'ᱱᱚᱸᱰᱮ ᱚᱞ',
    translate: 'ᱛᱚᱨᱡᱚᱢᱟ',
    translating: 'ᱛᱚᱨᱡᱚᱢᱟ ᱪᱟᱞᱟᱣ ᱠᱟᱱᱟ',
    chooseLanguage: 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ',
    searchLanguage: 'ᱯᱟᱹᱨᱥᱤ ᱯᱟᱱᱛᱮ',
    noLanguageFound: 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱝ ᱧᱟᱢ',
    tryAnotherWord: 'ᱮᱴᱟᱜ ᱥᱟᱵᱟᱫ ᱚᱞ',
    alertTranslateFailedTitle: 'ᱛᱚᱨᱡᱚᱢᱟ ᱵᱟᱝ ᱦᱩᱭᱩᱜ',
    alertSpeechFailedTitle: 'ᱨᱟᱣ ᱛᱚᱨᱡᱚᱢᱟ ᱵᱟᱝ ᱦᱩᱭᱩᱜ',
    alertWebNeededTitle: 'ᱣᱮᱵ ᱞᱟᱜᱤᱫ',
    alertWebNeededMessage: 'ᱱᱚᱣᱟ ᱵᱤᱞᱰ ᱨᱮ ᱨᱮᱠᱚᱨᱰᱤᱝ ᱠᱚ ᱞᱟᱜᱤᱫ ᱣᱮᱵ ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ।',
    alertMicPermissionTitle: 'ᱢᱟᱭᱠ ᱟᱱᱩᱢᱚᱫ ᱞᱟᱜᱤᱫ',
    alertMicPermissionMessage: 'ᱨᱮᱠᱚᱨᱰᱤᱝ ᱠᱚ ᱞᱟᱜᱤᱫ ᱢᱟᱭᱠ ᱟᱱᱩᱢᱚᱫ ᱮᱢᱚᱜ ᱢᱮ।',
    alertNoOutputTitle: 'ᱟᱫᱚ ᱛᱚᱨᱡᱚᱢᱟ',
    alertNoOutputMessage: 'ᱛᱟᱭᱚᱢ ᱟᱣᱟᱡ ᱟᱭᱠᱟᱹ।',
    alertVoiceUnavailableTitle: 'ᱟᱣᱟᱡ ᱵᱟᱝ ᱢᱮᱱᱟᱜᱼᱟ',
  },
  Sindhi: {
    statusReady: 'تيار',
    statusListening: 'ٻڌي رهيو آهي',
    statusWorking: 'ترجمو هلي رهيو آهي',
    languageWord: 'ٻوليون',
    from: 'کان',
    to: '۾',
    record: 'ڳالهايو',
    stop: 'روڪيو',
    listen: 'ٻڌو',
    playing: 'هلي رهيو آهي',
    resultLabel: 'نتيجو',
    resultTitle: 'نتيجو',
    speechResultTitle: 'آواز نتيجو',
    resultPlaceholder: 'ترجمو هتي ظاهر ٿيندو',
    voiceReady: 'آواز تيار آهي',
    inputLabel: 'انپٽ',
    inputTitle: 'لکو يا ڳالهايو',
    inputRecordingTitle: 'ريڪارڊنگ',
    inputPlaceholder: 'هتي لکو',
    translate: 'ترجمو ڪريو',
    translating: 'ترجمو ٿي رهيو آهي',
    chooseLanguage: 'ٻولي چونڊيو',
    searchLanguage: 'ٻولي ڳوليو',
    noLanguageFound: 'ٻولي نه ملي',
    tryAnotherWord: 'ٻيو لفظ لکو',
    alertTranslateFailedTitle: 'ترجمو نه ٿيو',
    alertSpeechFailedTitle: 'آواز جو ترجمو نه ٿيو',
    alertWebNeededTitle: 'ويب ضروري آهي',
    alertWebNeededMessage: 'هن بلڊ ۾ ريڪارڊنگ لاءِ ويب استعمال ڪريو.',
    alertMicPermissionTitle: 'مائڪرو فون اجازت گهرجي',
    alertMicPermissionMessage: 'ريڪارڊنگ لاءِ مائڪرو فون جي اجازت ڏيو.',
    alertNoOutputTitle: 'پهريان ترجمو ڪريو',
    alertNoOutputMessage: 'پوءِ آواز ٻڌو.',
    alertVoiceUnavailableTitle: 'آواز موجود ناهي',
  },
  Tamil: {
    statusReady: 'தயார்',
    statusListening: 'கேட்கிறது',
    statusWorking: 'மொழிபெயர்ப்பு நடக்கிறது',
    languageWord: 'மொழிகள்',
    from: 'இருந்து',
    to: 'க்கு',
    record: 'பேசுங்கள்',
    stop: 'நிறுத்து',
    listen: 'கேளுங்கள்',
    playing: 'இயங்குகிறது',
    resultLabel: 'முடிவு',
    resultTitle: 'முடிவு',
    speechResultTitle: 'குரல் முடிவு',
    resultPlaceholder: 'மொழிபெயர்ப்பு இங்கே வரும்',
    voiceReady: 'ஒலி தயாராக உள்ளது',
    inputLabel: 'உள்ளீடு',
    inputTitle: 'எழுதுங்கள் அல்லது பேசுங்கள்',
    inputRecordingTitle: 'பதிவு',
    inputPlaceholder: 'இங்கே எழுதுங்கள்',
    translate: 'மொழிபெயர்க்கவும்',
    translating: 'மொழிபெயர்க்கப்படுகிறது',
    chooseLanguage: 'மொழியைத் தேர்வு செய்க',
    searchLanguage: 'மொழியைத் தேடுக',
    noLanguageFound: 'மொழி கிடைக்கவில்லை',
    tryAnotherWord: 'வேறு சொல்லை எழுதுங்கள்',
    alertTranslateFailedTitle: 'மொழிபெயர்ப்பு தோல்வி',
    alertSpeechFailedTitle: 'குரல் மொழிபெயர்ப்பு தோல்வி',
    alertWebNeededTitle: 'வெப் தேவை',
    alertWebNeededMessage: 'இந்த build-இல் பதிவு செய்ய web-ஐ பயன்படுத்தவும்.',
    alertMicPermissionTitle: 'மைக்ரோஃபோன் அனுமதி தேவை',
    alertMicPermissionMessage: 'பதிவுக்காக மைக்ரோஃபோன் அனுமதி அளிக்கவும்.',
    alertNoOutputTitle: 'முதலில் மொழிபெயர்க்கவும்',
    alertNoOutputMessage: 'பிறகு ஒலியை கேளுங்கள்.',
    alertVoiceUnavailableTitle: 'ஒலி கிடைக்கவில்லை',
  },
  Telugu: {
    statusReady: 'సిద్ధం',
    statusListening: 'వింటోంది',
    statusWorking: 'అనువాదం జరుగుతోంది',
    languageWord: 'భాషలు',
    from: 'నుంచి',
    to: 'కు',
    record: 'మాట్లాడండి',
    stop: 'ఆపండి',
    listen: 'వినండి',
    playing: 'నడుస్తోంది',
    resultLabel: 'ఫలితం',
    resultTitle: 'ఫలితం',
    speechResultTitle: 'శబ్ద ఫలితం',
    resultPlaceholder: 'అనువాదం ఇక్కడ కనిపిస్తుంది',
    voiceReady: 'శబ్దం సిద్ధం',
    inputLabel: 'ఇన్‌పుట్',
    inputTitle: 'రాయండి లేదా మాట్లాడండి',
    inputRecordingTitle: 'రికార్డింగ్',
    inputPlaceholder: 'ఇక్కడ రాయండి',
    translate: 'అనువదించండి',
    translating: 'అనువాదం జరుగుతోంది',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    searchLanguage: 'భాషను వెతకండి',
    noLanguageFound: 'భాష దొరకలేదు',
    tryAnotherWord: 'ఇంకో పదం ప్రయత్నించండి',
    alertTranslateFailedTitle: 'అనువాదం కాలేదు',
    alertSpeechFailedTitle: 'శబ్ద అనువాదం కాలేదు',
    alertWebNeededTitle: 'వెబ్ అవసరం',
    alertWebNeededMessage: 'ఈ బిల్డ్‌లో రికార్డింగ్ కోసం వెబ్ ఉపయోగించండి.',
    alertMicPermissionTitle: 'మైక్రోఫోన్ అనుమతి కావాలి',
    alertMicPermissionMessage: 'రికార్డింగ్ కోసం మైక్రోఫోన్ అనుమతి ఇవ్వండి.',
    alertNoOutputTitle: 'ముందు అనువదించండి',
    alertNoOutputMessage: 'తర్వాత శబ్దం వినండి.',
    alertVoiceUnavailableTitle: 'శబ్దం అందుబాటులో లేదు',
  },
  Urdu: {
    statusReady: 'تیار',
    statusListening: 'سن رہا ہے',
    statusWorking: 'ترجمہ ہو رہا ہے',
    languageWord: 'زبانیں',
    from: 'سے',
    to: 'میں',
    record: 'بولیں',
    stop: 'روکیں',
    listen: 'سنیں',
    playing: 'چل رہا ہے',
    resultLabel: 'نتیجہ',
    resultTitle: 'نتیجہ',
    speechResultTitle: 'آواز نتیجہ',
    resultPlaceholder: 'ترجمہ یہاں نظر آئے گا',
    voiceReady: 'آواز تیار ہے',
    inputLabel: 'ان پٹ',
    inputTitle: 'لکھیں یا بولیں',
    inputRecordingTitle: 'ریکارڈنگ',
    inputPlaceholder: 'یہاں لکھیں',
    translate: 'ترجمہ کریں',
    translating: 'ترجمہ ہو رہا ہے',
    chooseLanguage: 'زبان منتخب کریں',
    searchLanguage: 'زبان تلاش کریں',
    noLanguageFound: 'کوئی زبان نہیں ملی',
    tryAnotherWord: 'دوسرا لفظ لکھیں',
    alertTranslateFailedTitle: 'ترجمہ نہیں ہوا',
    alertSpeechFailedTitle: 'آواز کا ترجمہ نہیں ہوا',
    alertWebNeededTitle: 'ویب درکار ہے',
    alertWebNeededMessage: 'اس بلڈ میں ریکارڈنگ کے لیے ویب استعمال کریں۔',
    alertMicPermissionTitle: 'مائیکروفون اجازت چاہیے',
    alertMicPermissionMessage: 'ریکارڈنگ کے لیے مائیکروفون کی اجازت دیں۔',
    alertNoOutputTitle: 'پہلے ترجمہ کریں',
    alertNoOutputMessage: 'پھر آواز سنیں۔',
    alertVoiceUnavailableTitle: 'آواز دستیاب نہیں ہے',
  },
};

export const UI_SUBTITLES = {
  from: 'Source language',
  to: 'Target language',
  record: 'Record speech',
  listen: 'Play audio',
  result: 'Translation result',
  input: 'Type or speak',
  translate: 'Send for translation',
  modal: 'Select language',
  search: 'Search by English or native name',
} as const;

export function getUiCopy(language: string): UiCopy {
  return { ...ENGLISH_UI, ...(UI_COPY[language] ?? {}) };
}
